#if other transformers are loaded at the same time as handlebars the priority decides which one is used if
#there is another transformer which can convert the same types as handlebars the one with the highest priority wins
priority: 2
#the base directory to check for handlebars templates
directory: templates
#if true then if a response object is a map each key in the map becomes the name of a variable in the
#handlebars scope with it's value set to the map's value for that key
extract_values_from_maps: true
#If true then when an object is returned that is not a collection or primitive the fields names in the object
#become variables in the handlebars scope with the value of the variable being that of the field
extract_pojo_fields: true
# if the template name given to the template annotation doesn't have a file extension this is appended
template: ".handlebars"
#if true a template is loaded once from disk and cached in memory, otherwise it's fetched each time it's needed
cache_templates: true
enable_jackson_helper : true;
enable_markdown_helper : true;
enable_humanize_helper : true;
