#should temp uploaded files be deleted
delete_temp_on_exit : true
#use default system temp dir if null
temp_directory:
#how big are the chunks when sending a static file
chunk_size : 8192
#a map of file extensions to their content type.
#any file with one of these extensions is sent with the given content-type header
custom_mime_types :
  htm,html : text/html
  json : application/json
  xml : application/xml
  png : image/png
  js :  application/javascript
  css:  text/css
  otf:  font/opentype
  svg:  image/svg+xml
  ttf:  application/x-font-truetype
  otf:  application/x-font-opentype
  woff: application/font-woff
  eot:  application/vnd.ms-fontobject
